-- Seed: users
-- role_id: 1=ADMIN, 2=DOCTOR, 3=RECEPTIONIST, 4=PHARMACIST, 5=PATIENT
-- NOTE: password_hash values below are PLACEHOLDERS. Replace with real
-- BCrypt hashes generated by the application before using in any real
-- environment.
USE hospital_management;

INSERT INTO users (role_id, username, email, password_hash) VALUES
    (1, 'admin',        'admin@hms.local',       '$2a$10$replaceWithRealBCryptHash01'),
    (2, 'dr.sharma',    'sharma@hms.local',      '$2a$10$replaceWithRealBCryptHash02'),
    (2, 'dr.gupta',     'gupta@hms.local',       '$2a$10$replaceWithRealBCryptHash03'),
    (3, 'reception1',   'reception1@hms.local',  '$2a$10$replaceWithRealBCryptHash04'),
    (4, 'pharmacist1',  'pharmacist1@hms.local', '$2a$10$replaceWithRealBCryptHash05'),
    (5, 'patient1',     'aarav.mehta@mail.com',  '$2a$10$replaceWithRealBCryptHash06');
