import { useState } from "react";
import { Alert, Box, Button, CircularProgress, Paper, TextField, Typography } from "@mui/material";
import { addAvailability, deleteAvailability, getAvailability, updateAvailability } from "../services/doctorService";
import type { Availability, AvailabilityRequest } from "../types/clinical";

const emptyRequest: AvailabilityRequest = { dayOfWeek: "MON", startTime: "09:00", endTime: "17:00" };
export default function Availability() {
  const [doctorId, setDoctorId] = useState("");
  const [rows, setRows] = useState<Availability[]>([]);
  const [request, setRequest] = useState<AvailabilityRequest>(emptyRequest);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const load = async () => { const id = Number(doctorId); if (!id) { setError("Doctor ID is required."); return; } try { setLoading(true); setError(""); setRows(await getAvailability(id)); } catch { setError("Unable to load availability."); } finally { setLoading(false); } };
  const save = async () => { const id = Number(doctorId); if (!id || request.startTime >= request.endTime) { setError("Enter a valid doctor and time range."); return; } try { setLoading(true); setError(""); const saved = editingId ? await updateAvailability(id, editingId, request) : await addAvailability(id, request); setRows((current) => editingId ? current.map((row) => row.id === saved.id ? saved : row) : [...current, saved]); setEditingId(null); setRequest(emptyRequest); } catch { setError("Unable to save availability."); } finally { setLoading(false); } };
  const remove = async (availabilityId: number) => { const id = Number(doctorId); try { setLoading(true); await deleteAvailability(id, availabilityId); setRows((current) => current.filter((row) => row.id !== availabilityId)); } catch { setError("Unable to delete availability."); } finally { setLoading(false); } };
  return <Box sx={{ p: 3 }}><Typography variant="h4" sx={{ fontWeight: "bold", mb: 3 }}>Doctor Availability</Typography>{error && <Alert severity="error" sx={{ mb: 2 }}>{error}</Alert>}<Paper sx={{ p: 3, mb: 3, display: "grid", gap: 2, maxWidth: 640 }}><TextField label="Doctor ID" type="number" value={doctorId} onChange={(event) => setDoctorId(event.target.value)} /><Button variant="outlined" onClick={() => void load()}>Load</Button><TextField select slotProps={{ select: { native: true } }} label="Day" value={request.dayOfWeek} onChange={(event) => setRequest({ ...request, dayOfWeek: event.target.value as AvailabilityRequest["dayOfWeek"] })}><option value="MON">MON</option><option value="TUE">TUE</option><option value="WED">WED</option><option value="THU">THU</option><option value="FRI">FRI</option><option value="SAT">SAT</option><option value="SUN">SUN</option></TextField><TextField type="time" label="Start" value={request.startTime} onChange={(event) => setRequest({ ...request, startTime: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} /><TextField type="time" label="End" value={request.endTime} onChange={(event) => setRequest({ ...request, endTime: event.target.value })} slotProps={{ inputLabel: { shrink: true } }} /><Button variant="contained" disabled={loading} onClick={() => void save()}>{editingId ? "Update" : "Add"}</Button></Paper>{loading && rows.length === 0 ? <CircularProgress /> : rows.length === 0 ? <Typography color="text.secondary">No availability found.</Typography> : rows.map((row) => <Paper key={row.id} sx={{ p: 2, mb: 1, display: "flex", justifyContent: "space-between" }}><Typography>{row.dayOfWeek}: {row.startTime} - {row.endTime}</Typography><Box><Button onClick={() => { setEditingId(row.id); setRequest({ dayOfWeek: row.dayOfWeek as AvailabilityRequest["dayOfWeek"], startTime: row.startTime, endTime: row.endTime }); }}>Edit</Button><Button color="error" onClick={() => void remove(row.id)}>Delete</Button></Box></Paper>)}</Box>;
}