-- =====================================================================
-- 25_risk_alerts.sql
-- Hospital Management System — Analytics: AI Risk Alerts
-- =====================================================================
-- Purpose:
--   Stores AI/rule-based clinical risk alerts generated by the
--   analytics engine (e.g. sepsis risk, emergency priority escalation,
--   critical vitals). Acknowledged_by references the user who cleared
--   the alert.
-- =====================================================================

USE hospital_management;

CREATE TABLE risk_alerts (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    patient_id          BIGINT NOT NULL,
    alert_type          ENUM('SEPSIS_RISK','EMERGENCY_PRIORITY',
                             'VITALS_CRITICAL','MEDICATION_ALERT',
                             'FALL_RISK','READMISSION_RISK','OTHER')
                            NOT NULL,
    severity            ENUM('LOW','MEDIUM','HIGH','CRITICAL')
                            NOT NULL DEFAULT 'MEDIUM',
    title               VARCHAR(200) NOT NULL,
    description         TEXT NOT NULL,
    source              VARCHAR(100) NULL,  -- e.g. "AI Model v1.2", "Rule Engine"
    is_acknowledged     BOOLEAN NOT NULL DEFAULT FALSE,
    acknowledged_by     BIGINT NULL,       -- user_id who acknowledged
    acknowledged_at     TIMESTAMP NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                            ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT fk_risk_alerts_patient
        FOREIGN KEY (patient_id) REFERENCES patients(id)
        ON DELETE CASCADE ON UPDATE CASCADE,

    CONSTRAINT fk_risk_alerts_acknowledged_by
        FOREIGN KEY (acknowledged_by) REFERENCES users(id)
        ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_risk_alerts_patient_id       ON risk_alerts(patient_id);
CREATE INDEX idx_risk_alerts_severity         ON risk_alerts(severity);
CREATE INDEX idx_risk_alerts_alert_type       ON risk_alerts(alert_type);
CREATE INDEX idx_risk_alerts_is_acknowledged  ON risk_alerts(is_acknowledged);
CREATE INDEX idx_risk_alerts_created_at       ON risk_alerts(created_at);
